#theme: jekyll-theme-slate
title: Civikbooks
author:
  name: juanfernandovillahernandez
  email: juan.villa@paisdelconocimiento.org
description: > # this means to ignore newlines until "show_excerpts:"
  Los Libros cívicos son plantillas para proyectos, soluciones a retos,
  necesidades y problemas comunes en Comunidades Inteligentes,
  Ciudades Inteligentes en el contexto de los Objetivos de Desarrollo Sostenible.
show_excerpts: true # set to true to show excerpts on the homepag

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
social_links:
    twitter: smartcitiesco
    github: smartcitiescommunity
    # devto: jekyll
    # dribbble: jekyll
    facebook: SmartCitiesCommunity
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: juanfernandovillahernandez
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCSNF2cnPhtm_0xWjyDBDxkA
    youtube_channel_name: Smart Cities Community
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-minimal

plugins:
 - jekyll-feed
 - jekyll-seo-tag
